config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  resources :users

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :admin do
    get 'features', to: "feature_flipper#index", as: :features_admin
    put 'features/:feature/flip', to: "feature_flipper#flip", as: :feature_flip
    resources :products
    put 'products/electricity/prices', to: "products#update_electricity_prices", as: :new_electricity_prices
    put 'products/gas/prices', to: "products#update_gas_prices", as: :new_gas_prices
  end

  get '/v1/companies', to: "api#companies"
  get '/v1/report', to: "api#report"
  get '/v1/mpans', to: "api#mpans"
  get '/v1/mprns', to: "api#mprns"
  get '/v1/meterpoint', to: "api#meterpoint"
  get '/v1/customer', to: "api#customer"
  get '/v1/agreements', to: "api#agreements"

  # proxy Junifer API calls
  get '/junifer/:request', to: "junifer#proxy", request: /[\/a-zA-z0-9]+/
  post '/junifer/:request', to: "junifer#proxy", request: /[\/a-zA-z0-9]+/

  comfy_route :cms_admin, :path => '/admin'
  comfy_route :cms, :path => '/cms', :sitemap => true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Comfy::Admin::Cms::BaseController
  def index
    @electricity_products = ElectricityProduct.all
    @gas_products = GasProduct.all
  end

  def update_electricity_prices
    begin
      csv = File.read(params[:file].path).gsub(/\r\n?/, "\n")
      ElectricityProductUpload.start(csv)
      ElectricityProductUpload.finish
      flash[:notice] = 'New electricity prices available'
    rescue => e
      Rails.logger.warn e.inspect
      flash[:alert] = 'Unable to process electricity prices CSV'
    end
    redirect_to action: 'index'
  end

  def update_gas_prices
    begin
      csv = File.read(params[:file].path).gsub(/\r\n?/, "\n")
      GasProductUpload.start(csv)
      GasProductUpload.finish
      flash[:notice] = 'New gas prices available'
    rescue => e
      Rails.logger.warn e.inspect
      flash[:alert] = 'Unable to process gas prices CSV'
    end
    redirect_to action: 'index'
  end
end

app/views/admin/products/_electricity_product.html.haml
%td= product.profile_class
%td= product.distribution_area
%td= "#{product.duration} #{product.duration == 1 ? 'year' : 'years'}"
%td= product.rate1_name
%td= "#{product.standing_charge_rate} p/day"
%td= "#{product.rate1} p/kWh"
%td= "#{product.rate2} p/kWh" if product.rate2
%td= product.matrix_id

app/views/admin/products/_gas_product.html.haml
%td= product.matrix_id
%td= product.distribution_zone
%td= "#{product.duration} #{product.duration == 1 ? 'year' : 'years'}"
%td= product.lower_limit_aq
%td= product.upper_limit_aq
%td= "#{product.standing_charge_rate} p/day"
%td= "#{product.rate} p/kWh"

app/views/admin/products/index.html.haml
%h2 Electricity

%h3 Update prices

= form_tag admin_new_electricity_prices_path, method: :put, multipart: true do
  = file_field_tag :file, accept: "text/csv"
  %br/
  = submit_tag "Upload CSV"

- most_recent_product = ElectricityProduct.all.max_by(&:created_at)
%h3 Current prices [latest update: #{most_recent_product.created_at if most_recent_product}]

%table.table.table-striped.table-hover.table-bordered
  %thead.list
    %tr
      %th Profile class
      %th Distribution area
      %th Contract length
      %th Product name
      %th Standing charge
      %th Unit rate (standard/day)
      %th Unit rate (night)
      %th Matrix id
  %tbody.list
    - @electricity_products.each_with_index do |product, idx|
      %tr
        = render 'electricity_product', product: product

%h3 Gas

%h3 Update prices

= form_tag admin_new_gas_prices_path, method: :put, multipart: true do
  = file_field_tag :file, accept: "text/csv"
  %br/
  = submit_tag "Upload CSV"

- most_recent_product = GasProduct.all.max_by(&:created_at)
%h3 Current prices [latest update: #{most_recent_product.created_at if most_recent_product}]

%table.table.table-striped.table-hover.table-bordered
  %thead.list
    %tr
      %th Matrix id
      %th Distribution zone
      %th Contract length
      %th Lower AQ limit
      %th Upper AQ limit
      %th Standing charge
      %th Unit rate
  %tbody.list
    - @gas_products.each_with_index do |product, idx|
      %tr
        = render 'gas_product', product: product