config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  resources :users

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :admin do
    get 'features', to: "feature_flipper#index", as: :features_admin
    put 'features/:feature/flip', to: "feature_flipper#flip", as: :feature_flip
    resources :products
    put 'products/electricity/prices', to: "products#update_electricity_prices", as: :new_electricity_prices
    put 'products/gas/prices', to: "products#update_gas_prices", as: :new_gas_prices
  end

  get '/v1/companies', to: "api#companies"
  get '/v1/report', to: "api#report"
  get '/v1/mpans', to: "api#mpans"
  get '/v1/mprns', to: "api#mprns"
  get '/v1/meterpoint', to: "api#meterpoint"
  get '/v1/customer', to: "api#customer"
  get '/v1/agreements', to: "api#agreements"

  # proxy Junifer API calls
  get '/junifer/:request', to: "junifer#proxy", request: /[\/a-zA-z0-9]+/
  post '/junifer/:request', to: "junifer#proxy", request: /[\/a-zA-z0-9]+/

  comfy_route :cms_admin, :path => '/admin'
  comfy_route :cms, :path => '/cms', :sitemap => true
end

app/controllers/admin/feature_flipper_controller.rb
class Admin::FeatureFlipperController < Comfy::Admin::Cms::BaseController
  def index
    @features = Flipper::Adapters::ActiveRecord::Feature.all.map(&:key)
  end

  def flip
    feature = params[:feature].downcase.gsub(/[^a-z]/,'').to_sym
    if FF[feature].enabled?
      FF[feature].disable
    else
      FF[feature].enable
    end
    which_image = FF[feature].enabled? ? 'flip-on.png' : 'flip-off.png'
    url_for_toggle = ActionController::Base.helpers.asset_path(which_image)
    render json: {feature: feature, enabled: FF[feature].enabled?, image: url_for_toggle}
  end
end

app/views/admin/feature_flipper/index.html.haml
.page-header
  %h2= 'Features Admin'

%p
  Here you can enable/disable features without affecting the rest of the web site.
  %br/
  %br/

%table.table.table-striped.table-hover.table-bordered
  %tr
    %th Feature
    %th{style: 'text-align: right;'} Toggle
  - @features.each_with_index do |feature, idx|
    %tr
      %td{style: 'vertical-align: middle;'}= feature
      %td{style: 'text-align: right; vertical-align: middle;'}
        = form_tag admin_feature_flip_path(feature: feature), method: :put, remote: true, id: "toggle#{idx}" do
          - image_for_toggle = FF[feature.to_sym].enabled? ? 'flip-on.png' : 'flip-off.png'
          %input{type: 'image', src: asset_path(image_for_toggle), border: 0, alt: 'Submit', style: 'height: 32px; outline: none;'}
          :javascript
            $("form#toggle#{idx}").on('ajax:success', function(e, data, status, xhr) {
              $("form#toggle#{idx} input[type=image]").attr('src', data.image);
            });